<?php
/**
 * @author Vasilis Neris
 * @package FusionLab_Ga4
 */
/** @var \FusionLab\Ga4\Block\Head $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $escaper->escapeHtml($block->getContainerId())?>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
