<?php
/**
 * Copyright (c) 2025 Fusion Lab G.P
 * Website: https://fusionlab.gr
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** @var \FusionLab\Ga4\Block\Adminhtml\GtmJson $block */

?>

<div class="info">
    <h3><?php echo __('Get Started!') ?></h3>
    <h5><?php echo __('Download the JSON and import it on your Google Tag Manager Container.') ?></h5>
    <h5><?php echo __('Navigate to your Google Tag Manager container and click admin, then click import container.') ?></h5>
    <img src="<?php echo $block->getViewFileUrl('FusionLab_Ga4::images/get-started-admin.png') ?>"/>
    <img src="<?php echo $block->getViewFileUrl('FusionLab_Ga4::images/get-started-import.png') ?>"/>
</div>

<div class="control">
    <a href="<?php echo $block->getJsonFileUrl(); ?>" download class="action-default">
        <?php echo __('Download JSON File'); ?>
    </a>
</div>
